### ISSUE TITLE
led not working

### ISSUE THREAD

**Issue by Velt1** [Bin4ry/free-dog-sdk#1]
The leds are not working i guess.
I tried it over doing
hstate.led = led(0, 255, 0)

**Comment by Bin4ry** [comment]
I am going to check LED function again, but next week as i am travelling for work now.

BUT you are doing it wrong.
you are using the state not the cmd. So the hstate is the highState that you receive from the dog, what you send to the dog is the highCmd, hCmd in the speak.py example. Long story short: Cmd is send TO the dog, state is read FROM the dog.
So what you want to do is to set the led via the hCmd, see the full highCmd class here:
https://github.com/Bin4ry/free-dog-sdk/blob/main/ucl/highCmd.py

So in the speak.py example there is:
hcmd.mode = Mode.VEL_WALK
hcmd.gaitType = GaitType.TROT
hcmd.velocity = [0.04, 0.1]
hcmd.yawSpeed = 2
hcmd.footRaiseHeight = 0.1
hcmd.encrypt = False
cmd_bytes = hcmd.buildCmd(debug=True)
conn.send(cmd_bytes)

try adding at the top:
from ucl.complex import led

and BEFORE cmd_bytes = ..... add this:
hcmd.led = led(0,255,0) 

then run again the speak.py
