### ISSUE TITLE
Sryy to post it like that but the slack invite have been expired

### ISSUE THREAD

**Issue by karimPM** [Bin4ry/free-dog-sdk#14]
Thank you for your great effort 

Sryy to post it like that but the slack invite have been expired 

Can you please renew it

**Comment by MAVProxyUser** [comment]
new non expiring link added. https://join.slack.com/t/robotdogs/shared_invite/zt-24ep8mqn4-1p42Aq7owRv9klLI~3C5Pw

**Comment by karimPM** [comment]
Thank you, really appreciate it

**Comment by gestalt73** [comment]
The slack channel used to be open to all, but now only to @unitree.cc and @u.northwestern.edu?

**Comment by marios-stam** [comment]
That's a valid question. Could you please inform me what is the process for getting an email like that?

**Comment by gestalt73** [comment]
Here's what I see when I click on the updated link posted above by @MAVProxyUser:
![Screenshot from 2023-12-29 10-33-46](https://github.com/Bin4ry/free-dog-sdk/assets/7560718/4223a37f-5476-4fb0-a716-6b9a0dd5cc98)

**Comment by MAVProxyUser** [comment]
We had a lot of dead weight so I pruned the channel heavily, and deleted the links: Here is a fresh link, it will expire in 28 days. https://join.slack.com/t/robotdogs/shared_invite/zt-29ko4lpye-N~9OPznkScHwR~LBduFSmg

**Comment by aning-liu** [comment]
Hi, could you post the link again?
