### ISSUE TITLE
Could you add me to the slack channel?

### ISSUE THREAD

**Issue by johnny-wang16** [Bin4ry/free-dog-sdk#20]
I came from the youtube video for Go1 Teardown / Main Board Removal Disassembly. Could you add me to the slack channel? Id like to know the screw bit sizes you used. Thanks!

**Comment by johnny-wang16** [comment]
My email is tstmwcbm@gmail.com

**Comment by aning-liu** [comment]
Could you also add me to the channel? My email is xuanning.lucy.liu@gmail.com

**Comment by MAVProxyUser** [comment]
You've both been invited... just now.
