### ISSUE TITLE
So no need to mangle with internals using this SDK for non-EDU?

### ISSUE THREAD

**Issue by ex3ndr** [Bin4ry/free-dog-sdk#5]
Hey! Awesome project, i just got g1 air for my locomotion project. But i am puzzled does this mean that we don't need to have any firmware tweaks to make it work unlike official one?

**Comment by MAVProxyUser** [comment]
Correct... the pay to play limitation of EDU dog using LOW level is artificial. Air, Pro, and MAX can all use Low level commands, not just EDU. No firmware tweaks required.

**Comment by MAVProxyUser** [comment]
If this helped you to save money feel free to donate to help source more robot dogs :) https://www.buymeacoffee.com/bin4ry
