### ISSUE TITLE
Euler while walking

### ISSUE THREAD

**Issue by Carbon225** [Bin4ry/free-dog-sdk#9]
https://github.com/unitreerobotics/unitree_legged_sdk/issues/72

Since the remote can do it, is it just missing from the official sdk?
What about this hacked version? I my experiments I could not get the dog to respond to euler commands outside of `FORCED_STAND`. It is somehow possible?

**Comment by MAVProxyUser** [comment]
this SDK is a reversed version of the original SDK, so IF it is possible in original SDK, it should be possible here. If not, it is likely not possible here since we are speaking to services that run on the dog itself.

**Comment by Carbon225** [comment]
Right, then it's probably not possible.

BTW, is it possible to talk to the cheetah code bypassing unitree code running on the raspberry? Originally I hoped that we could throw out everything running on the raspberry and Jetsons and send commands to the stm32. But does the unitree code actually contain core functionality like walking sequences?

P.S. Great library, I found it actually works better than the original

**Comment by Bin4ry** [comment]
That would be lowlevel mode, lowlevel speaks directly to the stm32.
Highlevel speaks to the legged_sport binary which then speaks to stm32 via lowlevel itself.
But in lowlevel you would need to control everything yourself ofc :)

**Comment by Carbon225** [comment]
Ok, thanks.
